version: '3.8'

services:
  api1:
    image: api-desafio:latest
    ports:
      - "8081:8080"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "250MB"
    depends_on:
      - database

  api2:
    image: api-desafio:latest
    ports:
      - "8082:8080"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "250MB"
    depends_on:
      - database

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: rinha
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - ./desafio/script.sql:/docker-entrypoint-initdb.d/script.sql
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"

  frontend:
    build:
      context: ./desafio-front
    ports:
      - "3000:80"

  nginx:
    image: nginx:latest
    volumes:
      - ./desafio/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      - api1
      - api2
      - database
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"