version: '3.8'

services:
  api1:
    image: api-desafio:latest
    ports:
      - "8081:8080"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "250MB"

  api2:
    image: api-desafio:latest
    ports:
      - "8082:8080"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "250MB"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"

  database:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "2222:5432"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"
